### ISSUE TITLE
Content Creator: Cannot add movie

### ISSUE THREAD

**Issue by anandamous** [UAF-Software-Construction-CS-372/Software-Construction-Project#22]
User role: Content Creator
Action: Adding movie
Issue: Cannot add movie due to Validation Error: Movie Creation Fails Due to Missing 'Feedback' Field

**Comment by kjlambries** [comment]
Use embed link

**Comment by anandamous** [comment]
That was a different issue, this is when the content creator/editor is adding a movie. For some reason the server does not like having a "null"/nothing feedback field as default. I think the fix would be to explicitly make the feedback field a blank quote instead of "null"/nothing

**Comment by kjlambries** [comment]
Ok hold on let me check that

**Comment by kjlambries** [comment]
Ah ok, I think it might be a feedback page not working yet issue

**Comment by kjlambries** [comment]
We fixed this by making the feedback field not required.

**Comment by anandamous** [comment]
Adding movies now works without crashing
