### ISSUE TITLE
Cannot view movie

### ISSUE THREAD

**Issue by anandamous** [UAF-Software-Construction-CS-372/Software-Construction-Project#23]
User role: Viewer
Action: Adding movie
Issue: Cannot view movie, the youtube video embedder does not properly display the video, with message "youtube.com refused to connect"

**Comment by kjlambries** [comment]
Use embed link

**Comment by kjlambries** [comment]
Testers retest

**Comment by kjlambries** [comment]
Adding instructions to the README make sure the Content Creator uses the right link when adding a movie.

**Comment by anandamous** [comment]
Viewing movies now works with embed link
