### ISSUE TITLE
Viewer cannot like movie

### ISSUE THREAD

**Issue by anandamous** [UAF-Software-Construction-CS-372/Software-Construction-Project#24]
User role: Viewer
Action: Liking a movie
Issue: Liking any video crashes the server
Error:
Adding new like: viewer_ -> rim
C:\Users\salmo\Documents\shitty website\Software-Construction-Project\server.js:184
  if (movie_like.likes.includes(req.body.user))
                       ^

TypeError: Cannot read properties of undefined (reading 'includes')
    at C:\Users\salmo\Documents\shitty website\Software-Construction-Project\server.js:184:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.0

**Comment by kjlambries** [comment]
No longer crashes when liking a video

**Comment by kjlambries** [comment]
Testers recheck issue

**Comment by kjlambries** [comment]
We have fixed this issue by calling the array properly ("likes[0]" instead of having "likes" due to the fact that we forgot that it was an array).

**Comment by anandamous** [comment]
Ok so the button doesn't crash the website/server but it doesn't seem to properly add the like. I'm assumnig it's supposed to add the user who liked the video into the array. It adds absolutely nothing. The console says the movie got liked but there is nothing updated to the actual movie

Movie title: movie title
New like added.
Adding new like: an_nd -> movie title
Movie found: {
  _id: new ObjectId('662702567ee0d76ca5334a24'),
  title: 'movie title',
  genre: 'horror',
  link: 'https://www.youtube.com/embed/lg647NcK8dI?si=IK4on0oDfi9mRE1J',
  likes: [],
  feedback: '',
  comments: [],
  __v: 0
}
Movie title: movie title
New like added.

**Comment by kalebvonburris** [comment]
This appears to be fixed one the `main` branch, Please retest.

**Comment by anandamous** [comment]
Movie like now works and does not crash the website
