### ISSUE TITLE
Marketing Manager does not get redirected to their home page when logging in

### ISSUE THREAD

**Issue by anandamous** [UAF-Software-Construction-CS-372/Software-Construction-Project#25]
User role: Marketing Manager
Action: Logging in
Issue: Does not get redirected to their home page when logging in. The page is blank when the "redirect" happens.

**Comment by kjlambries** [comment]
Marketing Manager is directed to feedback page, which is not completely working but is now redirected.

**Comment by kalebvonburris** [comment]
Guh!!!!

**Comment by kjlambries** [comment]
??

**Comment by anandamous** [comment]
Marketing Manager properly gets redirected to their respective homepage
